version: '3'
services:
  web:
    image: caddy
    restart: always
    cap_add:
        - NET_ADMIN
    ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
    volumes:
            - ./vol/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./vol/caddy/web:/srv:ro
            - caddy_data:/data
            - caddy_config:/config
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    command: run  -config /etc/v2ray/config.toml
    expose:
        - "10010"
    volumes:
        - ./vol/v2ray/config.toml:/etc/v2ray/config.toml:ro

volumes:
        caddy_data:
                external: true
        caddy_config:
